# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agenda.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61genda.proto\x12\x06\x61genda\x1a\x1bgoogle/protobuf/empty.proto\"&\n\x07\x43ontact\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05phone\x18\x02 \x01(\t\"1\n\x0c\x43ontactsList\x12!\n\x08\x63ontacts\x18\x01 \x03(\x0b\x32\x0f.agenda.Contact\"2\n\x08Response\x12\x11\n\tisSuccess\x18\x01 \x01(\x08\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t2\xaf\x02\n\rAgendaService\x12=\n\x0f\x43heckConnection\x12\x16.google.protobuf.Empty\x1a\x10.agenda.Response\"\x00\x12@\n\x0eGetAllContacts\x12\x16.google.protobuf.Empty\x1a\x14.agenda.ContactsList\"\x00\x12\x31\n\nAddContact\x12\x0f.agenda.Contact\x1a\x10.agenda.Response\"\x00\x12\x34\n\rRemoveContact\x12\x0f.agenda.Contact\x1a\x10.agenda.Response\"\x00\x12\x34\n\rUpdateContact\x12\x0f.agenda.Contact\x1a\x10.agenda.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agenda_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONTACT']._serialized_start=53
  _globals['_CONTACT']._serialized_end=91
  _globals['_CONTACTSLIST']._serialized_start=93
  _globals['_CONTACTSLIST']._serialized_end=142
  _globals['_RESPONSE']._serialized_start=144
  _globals['_RESPONSE']._serialized_end=194
  _globals['_AGENDASERVICE']._serialized_start=197
  _globals['_AGENDASERVICE']._serialized_end=500
# @@protoc_insertion_point(module_scope)
