# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import gRPCModels.sync.agendas_sync_pb2 as agendas__sync__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class SyncAgendaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SyncAgendas = channel.unary_unary(
                '/agenda_sync.SyncAgendaService/SyncAgendas',
                request_serializer=agendas__sync__pb2.SyncContactsList.SerializeToString,
                response_deserializer=agendas__sync__pb2.SyncResponse.FromString,
                )
        self.SyncFromOthers = channel.unary_unary(
                '/agenda_sync.SyncAgendaService/SyncFromOthers',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=agendas__sync__pb2.SyncContactsList.FromString,
                )


class SyncAgendaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SyncAgendas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncFromOthers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SyncAgendaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SyncAgendas': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncAgendas,
                    request_deserializer=agendas__sync__pb2.SyncContactsList.FromString,
                    response_serializer=agendas__sync__pb2.SyncResponse.SerializeToString,
            ),
            'SyncFromOthers': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncFromOthers,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=agendas__sync__pb2.SyncContactsList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agenda_sync.SyncAgendaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SyncAgendaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SyncAgendas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agenda_sync.SyncAgendaService/SyncAgendas',
            agendas__sync__pb2.SyncContactsList.SerializeToString,
            agendas__sync__pb2.SyncResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SyncFromOthers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agenda_sync.SyncAgendaService/SyncFromOthers',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            agendas__sync__pb2.SyncContactsList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
